public class SimpleCalculator {
    
    public simpleCalculator(){
        
    }
    public static Integer addNumbers(Integer a, Integer b){
        system.debug('Adding ' + a + ' and ' + b);
        return a + b;
    }
    public static Integer multiplyNumbers(Integer a, Integer b){
        
        return a * b;
    }
    public static Integer subtraction(Integer a, Integer b){
        
        return a - b;
    }

}